version: "3.9"

services:
  stickerbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stickerbot
    restart: unless-stopped
    volumes:
      - wwjs_session:/app/.wwebjs_auth
    environment:
      - SESSION_PATH=/app/.wwebjs_auth

volumes:
  wwjs_session:
